export const TOPIC_TAXONOMY = [
  "monetary-policy",
  "banking-sector",
  "stock-markets",
  "mutual-funds",
  "startup-funding",
  "venture-capital",
  "sebi-regulation",
  "rbi-policy",
  "union-budget",
  "corporate-earnings",
  "real-estate",
  "ev-sector",
  "renewable-energy",
  "oil-gas",
  "pharma",
  "fintech",
  "edtech",
  "ecommerce",
  "manufacturing",
  "exports-imports",
  "inflation",
  "gdp",
  "employment",
  "taxation",
  "msme",
  "ipo",
  "mergers-acquisitions",
  "foreign-investment",
  "cryptocurrency",
  "trade-policy",
  "it-sector",
  "telecom",
  "agriculture",
  "infrastructure",
  "defence",
  "retail",
  "hospitality",
  "aviation",
  "insurance",
  "pension"
] as const;

export type TopicSlug = (typeof TOPIC_TAXONOMY)[number];
